### ISSUE TITLE
CUDA Error "libcufft.so.10.0"

### ISSUE THREAD

**Issue by maschere** [zpzim/SCAMP#46]
I successfully built and installed pyscamp under Ubuntu 18.04, Python 3.7, CUDA 10.2 using the command "FORCE_CUDA=1 pip install -I --no-cache-dir pyscamp".

Hower upon running "import pyscamp as mp" I get the following error:
ImportError: libcufft.so.10.0: cannot open shared object file: No such file or directory

It seems like it is looking for CUDA 10.0 instead of CUDA 10.2... any help appreciated.

**Comment by zpzim** [comment]
Hi, thanks for creating the issue,

Is CUDA 10.0 also installed on your system?

Can you run the same command with -v and post the cmake output here? (you don't have to post any of the build warnings) This will be helpful.

**Comment by maschere** [comment]
Thanks for the quick response.
I'm attaching the full output of "FORCE_CUDA=1 pip install -I --no-cache-dir -v pyscamp".

Weirdly enough, nvcc --version tells me 10.0 is installed. But nvidia-smi tells me it's 10.2 (please note I'm using a pre-configured AWS "Deep Learning AMI Version 30.0" and it looks like it has CUDA 10.0, 10.1 and 10.2 preinstalled. I haven't installed CUDA / cudnn myself)

[cmake.log](https://github.com/zpzim/SCAMP/files/5005437/cmake.log)

**Comment by zpzim** [comment]
So pyscamp is being compiled using CUDA 10.0 in that log. The AMI is probably set up differently and has not configured the LD_LIBRARY_PATH

Can you try the following on the AMI and then try pyscamp again?

`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/cuda/lib64`

I think this will fix your issue, but it is troublesome that this is happening. I'll need to add to the troubleshooting tips in case other people are running into this issue.

**Comment by maschere** [comment]
Thank you very much, that fixed the issue.
